import { z } from "genkit";
import { ai } from "../../../../ai/ai.server";

export const critiqueAgent = ai.definePrompt({
	name: 'critiqueAgent',
	description: 'A critique agent that evaluates the quality of responses',
	system: `You are an AI critique agent.
    Your goal is to evaluate the quality of responses generated by other agents.
	Create a list of possible improvements for the following text.
	Critique the response for clarity, grammar, and readability.
	Do not suggest changes to the meaning of the text.`,
	input: {
		schema: z.object({
			response: z.string().describe('The response text to critique')
		})
	},
	output: {
		schema: z.object({
			critiques: z.array(z.string()).describe('A list of helpful critiques for improving the response')
		})
	},
	prompt: 'Critique the following response: {{response}}'
});